version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: electron-store
    versions:
    - 7.0.0
    - 7.0.1
    - 7.0.2
    - 7.0.3
  - dependency-name: "@octokit/rest"
    versions:
    - 18.0.15
    - 18.1.0
    - 18.1.1
    - 18.2.0
    - 18.2.1
    - 18.3.0
    - 18.3.1
    - 18.3.2
    - 18.3.3
    - 18.3.4
    - 18.3.5
    - 18.4.0
    - 18.5.0
    - 18.5.2
  - dependency-name: "@sentry/electron"
    versions:
    - 2.2.0
    - 2.3.0
    - 2.4.0
  - dependency-name: "@material/ripple"
    versions:
    - 10.0.0
    - 9.0.0
  - dependency-name: "@material/icon-button"
    versions:
    - 10.0.0
    - 9.0.0
  - dependency-name: "@material/switch"
    versions:
    - 10.0.0
    - 9.0.0
